apiVersion: apps/v1
kind: Deployment
metadata:
  name: allcome
spec:
  replicas: 1
  selector:
    matchLabels:
      app: allcome
  template:
    metadata:
      labels:
        app: allcome
    spec:
      containers:
      - image: okteto.dev/allcome:latest
        name: allcome
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "793247a3-deeb-4f23-a732-d7dee6b4810f"
        - name: Vless_Path
          value: "/793247a3-deeb-4f23-a732-d7dee6b4810f-vless"
        - name: Vmess_UUID
          value: "793247a3-deeb-4f23-a732-d7dee6b4810f"
        - name: Vmess_Path
          value: "/793247a3-deeb-4f23-a732-d7dee6b4810f-vmess"
        - name: Share_Path
          value: "/v2link"
